config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  constraints subdomain: "admin" do
    scope module: "admin", as: "admin" do
      # Redirect /admin to the dashboard page.
      root to: redirect("dashboard")
      resources :dashboard
      resources :users
      resources :game_ids, path: "game-ids"
    end

    devise_for :users,
      path: "",
      controllers: {
        sessions: "users/sessions",
        passwords: "users/passwords"
      },
      path_names: {
        sign_in: "/login",
        password: "/forgot",
        sign_out: "/logout"
      }

    mount Sidekiq::Web => "/sidekiq"
  end

  root to: "home#index"

  get "music-np-banner/lastfm",
    to: "music_np_banner#lastfm",
    constraints: lambda { |req| ["html", "svg"].include? req.format }
  get "music-np-banner/listenbrainz",
    to: "music_np_banner#listenbrainz",
    constraints: lambda { |req| ["html", "svg"].include? req.format }
  resources :anilist, only: [:index, :new, :show] do
    collection do
      get "fetch_followers"
    end
  end
  resources :discord_banner,
    path: "discord-banner",
    only: :index,
    constraints: lambda { |req| ["html", "svg"].include? req.format }
  get "ping", to: "home#ping"
  get "anilist_user_activities", to: "home#anilist_user_activities"
  get "anilist_user_statistics", to: "home#anilist_user_statistics"
  get "watched_anime_section", to: "home#watched_anime_section"
  get "watched_movie_section", to: "home#watched_movie_section"
  get "lastfm_stats", to: "home#lastfm_stats"
  get "lastfm_top_artists", to: "home#lastfm_top_artists"
  get "browserconfig", to: "home#browserconfig", constraints: lambda { |req| req.format == :xml }, as: "browserconfig"
  get "site", to: "home#site", constraints: lambda { |req| req.format == :webmanifest }, as: "webmanifest"

  # error pages
  %w(400 403 404 405 406 409 422 500 501).each do |code|
    get code, to: "exceptions#index", defaults: { code: }
  end
end

app/models/game_id.rb
# frozen_string_literal: true

class GameId
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :ign, type: String
  field :game_id, type: String
  field :icon_name, type: String
  field :icon_filename, type: String
  field :icon_url, type: String
  field :status, type: Integer, default: 1

  index({ game_id: 1 }, { unique: true })
end

app/controllers/admin/game_ids_controller.rb
# frozen_string_literal: true

module Admin
  class GameIdsController < AdminController
    before_action :set_game_id, only: %i[ show edit update destroy ]

    # GET /admin/game-ids or /admin/game-ids.json
    def index
      @game_ids = GameId.all
    end

    # GET /admin/game-ids/1 or /admin/game-ids/1.json
    def show
      # show
    end

    # GET /admin/game-ids/new
    def new
      @game_id = GameId.new
    end

    # GET /admin/game-ids/1/edit
    def edit
      # edit
    end

    # POST /admin/game-ids or /admin/game-ids.json
    def create
      @game_id = GameId.new(game_id_params)

      respond_to do |format|
        if @game_id.save
          format.html { redirect_to [:admin, @game_id], notice: "Game ID was successfully created." }
          format.json { render :show, status: :created, location: @game_id }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @game_id.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/game-ids/1 or /admin/game-ids/1.json
    def update
      respond_to do |format|
        if @game_id.update(game_id_params)
          format.html { redirect_to [:admin, @game_id], notice: "Game ID was successfully updated." }
          format.json { render :show, status: :ok, location: @game_id }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @game_id.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/game-ids/1 or /admin/game-ids/1.json
    def destroy
      @game_id.destroy
      redirect_to admin_social_links_url, info: "Game ID was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_game_id
        @game_id = GameId.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def game_id_params
        params.require(:game_id).permit(:name, :ign, :game_id, :icon_name, :icon_filename, :icon_url, :status)
      end
  end
end

app/views/admin/game_ids/_form.html.erb
<div class="bg-gray-100">
  <div>
    <div class="md:grid md:grid-cols-3 md:gap-6">
      <div class="md:col-span-1">
        <div class="px-4 sm:px-0">
          <h3 class="text-lg font-medium leading-6 text-gray-900">Game ID</h3>
        </div>
      </div>
      <div class="mt-5 md:mt-0 md:col-span-2">
        <%= form_for [:admin, game_id], class: "w-full max-w-lg" do |f| %>
          <div class="shadow sm:rounded-md sm:overflow-hidden">
            <div class="px-4 py-5 space-y-6 bg-white sm:p-6">
              <div class="grid grid-cols-3 gap-6">
                <div class="col-span-3 sm:col-span-2">
                  <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>

                  <div class="flex mt-1 rounded-md shadow-sm">
                    <%= f.text_field :name, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: "Username" %>
                  </div>
                </div>
              </div>
              <div class="col-span-6 sm:col-span-4">
                <%= f.label :ign, class: "block text-sm font-medium text-gray-700" %>

                <%= f.text_field :ign, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: "IGN" %>
              </div>
              <div class="col-span-6 sm:col-span-4">
                <%= f.label :game_id, class: "block text-sm font-medium text-gray-700" %>

                <%= f.text_field :game_id, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: "Game ID" %>
              </div>
              <div class="col-span-6 sm:col-span-4">
                <%= f.label :icon_name, class: "block text-sm font-medium text-gray-700" %>

                <%= f.text_field :icon_name, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: "Icon Name" %>
              </div>
              <div class="col-span-6 sm:col-span-4">
                <%= f.label :icon_filename, class: "block text-sm font-medium text-gray-700" %>

                <%= f.text_field :icon_filename, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: "Icon Filename" %>
              </div>
              <div class="col-span-6 sm:col-span-4">
                <%= f.label :icon_url, class: "block text-sm font-medium text-gray-700" %>

                <%= f.text_field :icon_url, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: "Icon URL" %>
              </div>
            </div>
            <div class="px-4 py-3 text-right bg-gray-50 sm:px-6">
              <button type="submit" class="inline-flex justify-center px-4 py-2 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Save
              </button>

              <a type="button" href="<%= admin_game_ids_path %>" class="inline-flex justify-center px-4 py-2 text-sm font-medium text-white bg-red-600 border border-transparent rounded-md shadow-sm hover:bg-red-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                Back
              </a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/game_ids/edit.html.erb
<h1>Editing Game ID</h1>

<%= render "form", game_id: @game_id %>

app/views/admin/game_ids/index.html.erb
<h3 class="text-3xl font-medium text-gray-700">Game IDs</h3>

<div class="mt-8">
  <div class="mt-6">
    <div class="flex flex-col mt-3 sm:flex-row">
      <div class="flex">
        <div class="relative">
          <select class="block w-full h-full px-4 py-2 pr-8 leading-tight text-gray-700 bg-white border border-gray-400 rounded-l appearance-none focus:outline-none focus:bg-white focus:border-gray-500">
            <option>5</option>
            <option>10</option>
            <option>20</option>
          </select>
        </div>

        <div class="relative">
          <select class="block w-full h-full px-4 py-2 pr-8 leading-tight text-gray-700 bg-white border-t border-b border-r border-gray-400 rounded-r appearance-none sm:rounded-r-none sm:border-r-0 focus:outline-none focus:border-l focus:border-r focus:bg-white focus:border-gray-500">
            <option>All</option>
            <option>Active</option>
            <option>Inactive</option>
          </select>
        </div>
      </div>

      <div class="relative block mt-2 sm:mt-0">
        <span class="absolute inset-y-0 left-0 flex items-center pl-2">
          <iconify-icon icon="material-symbols:search" >
        </span>

        <input placeholder="Search" class="block w-full py-2 pl-8 pr-6 text-sm text-gray-700 placeholder-gray-400 bg-white border border-b border-gray-400 rounded-l rounded-r appearance-none sm:rounded-l-none focus:bg-white focus:placeholder-gray-600 focus:text-gray-700 focus:outline-none"/>
      </div>
    </div>

    <div class="flex flex-col mt-6">
      <div class="py-2 -my-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="inline-block min-w-full overflow-hidden align-middle border-b border-gray-200 shadow sm:rounded-lg">
          <table class="min-w-full">
            <caption>Users</caption>
            <thead>
              <tr>
                <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-gray-500 uppercase bg-gray-100 border-b border-gray-200">Name</th>
                <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-gray-500 uppercase bg-gray-100 border-b border-gray-200">IGN</th>
                <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-gray-500 uppercase bg-gray-100 border-b border-gray-200">Status</th>
                <th class="px-6 py-3 bg-gray-100 border-b border-gray-200"></th>
              </tr>
            </thead>

            <tbody class="bg-white">
              <% @game_ids.each do |game_id| %>
                <tr>
                  <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                    <div class="text-sm font-medium leading-5 text-gray-900">
                      <%= game_id.name %>
                    </div>
                  </td>

                  <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                    <div class="text-sm leading-5 text-gray-900">
                      <%= game_id.ign %>
                    </div>
                  </td>

                  <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                    <span class="inline-flex px-2 text-xs font-semibold leading-5 text-green-800 bg-green-100 rounded-full">
                      <%= game_id.status %>
                    </span>
                  </td>

                  <td class="px-6 py-4 text-sm font-medium leading-5 text-right whitespace-no-wrap border-b border-gray-200">
                    <div class="inline-flex space-x-4">
                      <%= link_to "Edit", edit_admin_game_id_path(game_id), class: "flex-1 px-6 py-3 bg-purple-600 rounded-md text-white font-medium tracking-wide hover:bg-purple-500 ml-3" %>
                      <%= link_to "Destroy", admin_game_id_path(game_id), class: "flex-1 px-6 py-3 bg-red-600 rounded-md text-white font-medium tracking-wide hover:bg-red-500 ml-3", data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <div class="flex flex-col items-center px-5 py-5 bg-white border-t xs:flex-row xs:justify-between">
            <span class="text-xs text-gray-900 xs:text-sm">Showing 1 to 4 of 50 Entries</span>

            <div class="inline-flex mt-2 xs:mt-0">
              <button class="px-4 py-2 text-sm font-semibold text-gray-800 bg-gray-300 rounded-l hover:bg-gray-400">Prev</button>
              <button class="px-4 py-2 text-sm font-semibold text-gray-800 bg-gray-300 rounded-r hover:bg-gray-400">Next</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/admin/game_ids/new.html.erb
<h1>New Game ID</h1>

<%= render "form", game_id: @game_id %>

app/views/admin/game_ids/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "Edit", edit_admin_game_id_path(@game_id) %>
|
<%= link_to "Back", admin_game_ids_path %>