config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  constraints subdomain: "admin" do
    scope module: "admin", as: "admin" do
      # Redirect /admin to the dashboard page.
      root to: redirect("dashboard")
      resources :dashboard
      resources :users
      resources :game_ids, path: "game-ids"
    end

    devise_for :users,
      path: "",
      controllers: {
        sessions: "users/sessions",
        passwords: "users/passwords"
      },
      path_names: {
        sign_in: "/login",
        password: "/forgot",
        sign_out: "/logout"
      }

    mount Sidekiq::Web => "/sidekiq"
  end

  root to: "home#index"

  get "music-np-banner/lastfm",
    to: "music_np_banner#lastfm",
    constraints: lambda { |req| ["html", "svg"].include? req.format }
  get "music-np-banner/listenbrainz",
    to: "music_np_banner#listenbrainz",
    constraints: lambda { |req| ["html", "svg"].include? req.format }
  resources :anilist, only: [:index, :new, :show] do
    collection do
      get "fetch_followers"
    end
  end
  resources :discord_banner,
    path: "discord-banner",
    only: :index,
    constraints: lambda { |req| ["html", "svg"].include? req.format }
  get "ping", to: "home#ping"
  get "anilist_user_activities", to: "home#anilist_user_activities"
  get "anilist_user_statistics", to: "home#anilist_user_statistics"
  get "watched_anime_section", to: "home#watched_anime_section"
  get "watched_movie_section", to: "home#watched_movie_section"
  get "lastfm_stats", to: "home#lastfm_stats"
  get "lastfm_top_artists", to: "home#lastfm_top_artists"
  get "browserconfig", to: "home#browserconfig", constraints: lambda { |req| req.format == :xml }, as: "browserconfig"
  get "site", to: "home#site", constraints: lambda { |req| req.format == :webmanifest }, as: "webmanifest"

  # error pages
  %w(400 403 404 405 406 409 422 500 501).each do |code|
    get code, to: "exceptions#index", defaults: { code: }
  end
end

app/controllers/anilist_controller.rb
# frozen_string_literal: true
# typed: true

class AnilistController < ApplicationController
  include FormatDateHelper
  before_action :check_if_from_cloudfront

  def index
    # index
  end

  def show
    @user = AnilistUser.find_by(job_id: params[:id])
    if @user.blank?
      raise ActionController::RoutingError.new("Not Found")

    end

    @following = @user.following
    @followers = @user.followers
    @following_count = @following.size
    @followers_count = @followers.size
  end
  def new
    # new
  end


  def fetch_followers
    @success = false
    username = T.let(params[:username], String).strip
    return @error = "Username can't be empty" if username.blank?

    captcha_valid = verify_recaptcha action: "captcha", minimum_score: 0.5
    unless captcha_valid || Rails.env.development?
      @error = "You're probably a bot, aren't you?"
      return render layout: false
    end

    cooldown = Rails.cache.fetch("ANILIST/FOLLOW_CHECKER_CD")
    if Time.zone.now.to_i <= cooldown.to_i && !Rails.env.development?
      cd_mins = cooldown - Time.zone.now
      return @error = "On cooldown, please try again after #{format_date(cd_mins, true, false)}."
    end

    @user = AnilistUser.find_by(username:)
    if @user.present? && @user.sync_in_progress?
      return @error = "User <strong>#{username}</strong> is already in the queue and is being processed!<br />Please wait for the result."
    end

    if @user.blank?
      user_id = query(AniList::UserIdQuery, username:).user.id
      @user = AnilistUser.new(
        _id: user_id,
        username:,
      )
    end

    @user.sync_in_progress = true
    @user.last_known_error = nil
    @user.save
    @job_id = AnilistFollowListCheckerJob.perform_async(@user._id)

    Rails.cache.fetch("ANILIST/FOLLOW_CHECKER_CD", expires_in: 30.minutes) do
      30.minutes.from_now
    end
    @success = true
  rescue Graphlient::Errors::ServerError => error
    logger.tagged("ANILIST", "fetch_followers") do
      logger.error(error.inner_exception)
    end

    case error.status_code
    when 429
      Rails.cache.write("ANILIST_FOLLOW_CHECKER_CD", expires_in: 5.minutes)
      @error = "We're being rate-limited by AniList API, please try again later."
    when 404
      Rails.cache.write("ANILIST_FOLLOW_CHECKER_CD", nil)
      @error = "User <strong>#{username}</strong> was not found or has a private profile."
    else
      @error = "Something went wrong, please try again later."
    end
  end
end

app/views/anilist/_container.html.erb
<% bgs = (1..10).to_a.shuffle %>

<section x-data="{swiper:null}">
  <div class="relative flex w-screen min-h-[calc(100vh-56px)] xs:min-h-[calc(100vh-116px)] max-h-[calc(100vh-56px)] xs:max-h-[calc(100vh-116px)] font-sans">
    <div id="anilist-carousel" class="absolute top-0 left-0 w-full h-full swiper" x-init="swiper = new Swiper('#anilist-carousel', { modules: [Navigation, Autoplay, EffectFade], effect: 'fade', loop: true, speed: 3000, threshold: 40, autoplay: { delay: 10000, disableOnInteraction: false }, fadeEffect: { crossFade: true }, }); swiper.translateTo(window.screen.width * -1, 0, false, false);">
      <div class="swiper-wrapper">
        <% bgs.each do |num| %>
          <div class="swiper-slide background-ailane-<%= num %>">
            <img src="<%= vite_asset_path "images/ailane-bg-#{num}.webp" %>" alt="carousel-item" class="hidden visually-hidden"/>
          </div>
        <% end %>
      </div>
    </div>
    <div class="relative z-10 flex w-full pointer-events-none bg-gradient-to-br from-cyan-500/80 to-pink-500/80 tablet:overflow-y-hidden">
      <%= yield %>
    </div>
  </div>
</section>

app/views/anilist/_new.html.erb
<% tooltip = "<strong>Case-sensitive</strong><br /><em>Due to AniList imposing tight limits on their API requests, checking will be done in the background and will be viewable at a later time. You can check the progress via the link that would be provided after.</em>" %>

<div class="container relative" x-data="{ submitDisabled: false }">
  <div class="relative dark:bg-fg--dark/80 dark:text-text--dark backdrop-blur-sm bg-fg--light/80 text-text--light flex flex-col gap-y-16 w-full items-center justify-center p-8 rounded-lg shadow-lg top-[calc(30%-56px)] xs:top-[calc(30%-116px)] pointer-events-auto">
    <div class="flex flex-col items-center gap-2">
      <img src="<%= vite_asset_url("images/anilist-logo.svg") %>" width="80" alt="AniList">
      <h1 class="text-3xl text-center font-mono animate-pulse">anilist follow checker</h1>
    </div>

    <%= form_with(url: fetch_followers_anilist_index_path, method: :get, data: { turbo_frame: "anilist" }, html: { class: "max-w-lg w-full flex flex-col flex-1 gap-3" }) do |f| %>
      <%= f.hidden_field :format, value: "turbo_stream" %>
      <div class="flex flex-row gap-2">
        <%= f.label :username, "AniList Username:", class: "block font-bold", autocomplete: "off" %>
        <iconify-icon icon="material-symbols:info" width="25" class="cursor-help" data-tippy="tooltip" data-tippy-content="<%= tooltip %>"/>
      </div>
      <%= f.text_field :username, class: "w-full block py-3 px-4 rounded-full border focus:shadow-none focus:border-cyan-500 focus:outline-none dark:bg-fg--dark bg-fg--light", autocomplete: "off" %>

      <div class="flex flex-row items-right justify-between gap-4 px-4">
        <span class="text-xs italic"></span>
        <button type="submit" class="flex items-center px-4 py-3 font-medium text-white rounded cursor-pointer bg-cyan-700 hover:bg-cyan-600 dark:disabled:bg-bg--dark dark:disabled:text-text--dark disabled:bg-bg--light disabled:text-text--light disabled:shadow-none" @click="submitDisabled = true" x-text="submitDisabled ? 'Checking...' : 'Check'">
        </button>
      </div>

      <%= turbo_frame_tag "recaptcha" do %>
        <div class="mb-3 row">
          <%= recaptcha_v3 action: "captcha", turbolinks: true %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/anilist/fetch_followers.turbo_stream.erb
<turbo-stream target="anilist" action="update">
  <template>
    <% if @error || !@success %>
      <%= render partial: "anilist/new", formats: [:html] %>

      <% if @error %>
        <script>
          Alpine.store("toasts").createToast("<%= @error.html_safe.force_encoding("UTF-8") %>", "error");
        </script>
      <% end %>
    <% else %>
      <div class="flex flex-col flex-1 w-full py-4 backdrop-blur-sm p6-4">
        <div class="max-w-sm mx-auto mb-6 font-sans text-3xl font-semibold text-center text-black dark:text-white">
          <div class="pointer-events-auto">
            <span class="dark:opacity-80">Take me</span>
            <%= link_to "Back", anilist_index_path, class: "hover:text-[#3DB4F2] border-b", target: "anilist" %>
          </div>
        </div>
        <div class="justify-items-center container relative text-center">
          <div class="max-w-lg w-full pb-5 border-b-4 border-blue-400 rounded-md pointer-events-auto dark:bg-fg--dark/90 bg-fg--light/80 h-fit mx-auto px-10 py-5 flex flex-col gap-4">
            <iconify-icon icon="material-symbols:check-circle-rounded" width="100" class="mx-auto text-green-400"></iconify-icon>
            <h1 class="text-2xl font-bold dark:text-text--dark text-text--light">
              Added to the queue successfully, processing might take some time and could also be delayed if there are a lot in the queue. Check its progress with the provided link below.
            </h1>
            <%= link_to "Link", anilist_path(id: @job_id), class: "flex items-center px-4 py-3 font-medium text-white rounded cursor-pointer bg-cyan-700 hover:bg-cyan-600  justify-center", data: { turbo: false } %>
          </div>
        </div>
      </div>
    <% end %>
  </template>
</turbo-stream>

app/views/anilist/index.html.erb
<%= render "anilist/container" do %>
  <turbo-frame id="anilist" class="flex justify-center flex-1">
    <%= render "anilist/new" %>
  </turbo-frame>
<% end %>

app/views/anilist/show.html.erb
<%= render "anilist/container" do %>
  <div class="flex flex-col flex-1 w-full py-4 backdrop-blur-sm p6-4">
    <div class="max-w-sm mx-auto mb-6 font-sans text-3xl font-semibold text-center text-black dark:text-white">
      <div class="pointer-events-auto">
        <span class="dark:opacity-80">Take me</span>
        <%= link_to "Back", anilist_index_path, class: "hover:text-[#3DB4F2] border-b", data: { turbo: false } %>
      </div>
    </div>
    <% if @user.sync_in_progress? %>
      <div class="justify-items-center container relative text-center">
        <div class="max-w-lg w-full pb-5 border-b-4 border-blue-400 rounded-md pointer-events-auto dark:bg-fg--dark/90 bg-fg--light/80 h-fit mx-auto px-10 py-5 flex flex-col gap-4">
          <iconify-icon icon="line-md:loading-alt-loop" width="100" class="mx-auto text-cyan-600"></iconify-icon>
          <h1 class="text-2xl font-bold dark:text-text--dark text-text--light">
            Still being processed, please check again later.
          </h1>
          <%= link_to "Reload", anilist_path(id: @user.job_id), class: "flex items-center px-4 py-3 font-medium text-white rounded cursor-pointer bg-cyan-700 hover:bg-cyan-600 justify-center", data: { turbo: false } %>
        </div>
      </div>
    <% elsif @user.last_known_error %>
      <div class="justify-items-center container relative text-center">
        <div class="max-w-lg w-full pb-5 border-b-4 border-blue-400 rounded-md pointer-events-auto dark:bg-fg--dark/90 bg-fg--light/80 h-fit mx-auto px-10 py-5 flex flex-col gap-4">
          <iconify-icon icon="material-symbols:error" width="100" class="mx-auto text-red-600"></iconify-icon>
          <h1 class="text-2xl font-bold dark:text-text--dark text-text--light">
            Something went wrong, please submit a new request."
          </h1>
        </div>
      </div>
    <% else %>
      <div class=" phone:grid-cols-1 dark:[color-scheme:dark] phone:overflow-y-auto tablet:grid-cols-2 tablet:overflow-y-auto desktop:grid-cols-4 desktop:my-auto desktop:overflow-hidden justify-items-center container relative grid justify-between gap-5 text-center ">
        <div class="w-full max-w-sm pb-5 border-b-4 border-blue-400 rounded-md pointer-events-auto dark:bg-fg--dark/90 bg-fg--light/80 h-fit tablet:h-full">
          <div class="sticky top-0 px-10 pt-5 mb-5 bg-transparent">
            <h1 class="text-2xl font-bold border-b-2 border-b-text--light dark:border-b-text--dark dark:text-text--dark text-text--light">
              <%= sanitize "Not Following You (<span class='text-[#3DB4F2]'>#{(@following - @followers).size}</span>)" %>
            </h1>
          </div>
          <ul class="desktop:h-[70vh] dark:[color-scheme:dark] desktop:overflow-y-auto list-none mx-5">
            <% (@following - @followers).each do |f| %>
              <li class="hover:text-cyan-400 dark:text-blue-400 text-[#5c728a] font-semibold">
                <%= link_to f, "https://anilist.co/user/#{f}", target: "_blank", rel: "noreferrer noopener" %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="w-full max-w-sm pb-5 border-b-4 border-blue-400 rounded-md pointer-events-auto dark:bg-fg--dark/90 bg-fg--light/80 h-fit tablet:h-full">
          <div class="sticky top-0 px-10 pt-5 mb-5 bg-transparent">
            <h1 class="text-2xl font-bold border-b-2 border-b-text--light dark:border-b-text--dark dark:text-text--dark text-text--light">
              <%= sanitize "You're Not Following (<span class='text-[#3DB4F2]'>#{(@followers - @following).size}</span>)" %>
            </h1>
          </div>
          <ul class="desktop:h-[70vh] dark:[color-scheme:dark] desktop:overflow-y-auto list-none mx-5">
            <% (@followers - @following).each do |f| %>
              <li class="hover:text-cyan-400 dark:text-blue-400 text-[#5c728a] font-semibold">
                <%= link_to f, "https://anilist.co/user/#{f}", target: "_blank", rel: "noreferrer noopener" %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="w-full max-w-sm pb-5 border-b-4 border-blue-400 rounded-md pointer-events-auto dark:bg-fg--dark/90 bg-fg--light/80 h-fit tablet:h-full">
          <div class="sticky top-0 px-10 pt-5 mb-5 bg-transparent">
            <h1 class="text-2xl font-bold border-b-2 border-b-text--light dark:border-b-text--dark dark:text-text--dark text-text--light">
              <%= sanitize "Following (<span class='text-[#3DB4F2]'>#{@following_count}</span>)" %>
            </h1>
          </div>

          <ul class="desktop:h-[70vh] dark:[color-scheme:dark] desktop:overflow-y-auto list-none mx-5">
            <% @following.each do |f| %>
              <li class="hover:text-cyan-400 dark:text-blue-400 text-[#5c728a] font-semibold">
                <%= link_to f, "https://anilist.co/user/#{f}", target: "_blank", rel: "noreferrer noopener" %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="w-full max-w-sm pb-5 border-b-4 border-blue-400 rounded-md pointer-events-auto dark:bg-fg--dark/90 bg-fg--light/80 h-fit tablet:h-full">
          <div class="sticky top-0 px-10 pt-5 mb-5 bg-transparent">
            <h1 class="text-2xl font-bold border-b-2 border-b-text--light dark:border-b-text--dark dark:text-text--dark text-text--light">
              <%= sanitize "Followers (<span class='text-[#3DB4F2]'>#{@followers_count}</span>)" %>
            </h1>
          </div>

          <ul class="desktop:h-[70vh] dark:[color-scheme:dark] desktop:overflow-y-auto list-none mx-5">
            <% @followers.each do |f| %>
              <li class="hover:text-cyan-400 dark:text-blue-400 text-[#5c728a] font-semibold">
                <%= link_to f, "https://anilist.co/user/#{f}", target: "_blank", rel: "noreferrer noopener" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
<% end %>