config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  constraints subdomain: "admin" do
    scope module: "admin", as: "admin" do
      # Redirect /admin to the dashboard page.
      root to: redirect("dashboard")
      resources :dashboard
      resources :users
      resources :game_ids, path: "game-ids"
    end

    devise_for :users,
      path: "",
      controllers: {
        sessions: "users/sessions",
        passwords: "users/passwords"
      },
      path_names: {
        sign_in: "/login",
        password: "/forgot",
        sign_out: "/logout"
      }

    mount Sidekiq::Web => "/sidekiq"
  end

  root to: "home#index"

  get "music-np-banner/lastfm",
    to: "music_np_banner#lastfm",
    constraints: lambda { |req| ["html", "svg"].include? req.format }
  get "music-np-banner/listenbrainz",
    to: "music_np_banner#listenbrainz",
    constraints: lambda { |req| ["html", "svg"].include? req.format }
  resources :anilist, only: [:index, :new, :show] do
    collection do
      get "fetch_followers"
    end
  end
  resources :discord_banner,
    path: "discord-banner",
    only: :index,
    constraints: lambda { |req| ["html", "svg"].include? req.format }
  get "ping", to: "home#ping"
  get "anilist_user_activities", to: "home#anilist_user_activities"
  get "anilist_user_statistics", to: "home#anilist_user_statistics"
  get "watched_anime_section", to: "home#watched_anime_section"
  get "watched_movie_section", to: "home#watched_movie_section"
  get "lastfm_stats", to: "home#lastfm_stats"
  get "lastfm_top_artists", to: "home#lastfm_top_artists"
  get "browserconfig", to: "home#browserconfig", constraints: lambda { |req| req.format == :xml }, as: "browserconfig"
  get "site", to: "home#site", constraints: lambda { |req| req.format == :webmanifest }, as: "webmanifest"

  # error pages
  %w(400 403 404 405 406 409 422 500 501).each do |code|
    get code, to: "exceptions#index", defaults: { code: }
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true
# typed: true

require "spotify"
require "lastfm"
require "shoko"
require "fanart"

class HomeController < ApplicationController
  include FormatDateHelper
  include Turbo::Frames::FrameRequest
  layout "application"
  before_action :check_if_from_cloudfront
  before_action :check_if_turbo_frame, only: %i(lastfm_stats lastfm_top_artists anilist_user_statistics anilist_user_activities watched_anime_section watched_movie_section)

  ANIME_FORMATS = ["TV", "TV_SHORT", "ONA"]
  IGNORED_USER_STATUS = ["plans to watch", "paused watching", "dropped"]
  ANIME_RELATIONS = ["PREQUEL", "SEQUEL", "PARENT", "SIDE_STORY", "ALTERNATIVE"]

  def index
    @game_ids = GameId.where(status: 1).order(id: :asc)
  end

  def anilist_user_statistics
    user_id = ENV.fetch("ANILIST_USER_ID")
    colors = ["#cc333f", "#00a0b0", "#eb6841", "#f6a4b8", "#edc951", "#b3cc57"]
    @user_statistics = AnilistUserStatistic
                         .find(user_id)
                         &.[]("statistics")
                         &.[]("anime") || {}

    case turbo_frame_request_id
    when "favorite_anime_genres"
      # genre stats
      genre_statistics = @user_statistics["genres"]&.sort_by { |genre| genre["count"] }&.reverse!&.first(6)&.map do |genre|
        { name: genre["genre"], count: genre["count"].to_i }
      end
      genre_total_count = genre_statistics&.pluck(:count)&.sum.to_i
      @genre_list = genre_statistics&.map&.with_index do |genre, index|
        percentage = ((genre[:count].to_d / genre_total_count) * 100).ceil

        {
          label: "#{genre[:name]} (#{percentage}%)",
          value: genre[:count],
          backgroundColor: colors[index]
        }
      end
      @genre_chart_data = JSON.generate({
        labels: @genre_list&.pluck(:label) || [],
        datasets: [
          {
            label: "Anime Count",
            data: @genre_list&.pluck(:value) || [],
            backgroundColor: @genre_list&.pluck(:backgroundColor) || [],
            hoverOffset: 4
          }
        ]
      })
    when "favorite_anime_studios"
      # studio stats
      studio_statistics = @user_statistics["studios"]&.sort_by { |genre| genre["count"] }&.reverse!&.first(6)&.map do |studio|
        { name: studio["studio"]["name"], count: studio["count"].to_i }
      end
      studio_total_count = studio_statistics&.pluck(:count)&.sum.to_i
      @studio_list = studio_statistics&.map&.with_index do |studio, index|
        percentage = ((studio[:count].to_d / studio_total_count) * 100).ceil

        {
          label: "#{studio[:name]} (#{percentage}%)",
          value: studio[:count],
          backgroundColor: colors[index]
        }
      end
      @studio_chart_data = JSON.generate({
        labels: @studio_list&.pluck(:label) || [],
        datasets: [
          {
            label: "Anime Count",
            data: @studio_list&.pluck(:value) || [],
            backgroundColor: @studio_list&.pluck(:backgroundColor) || [],
            hoverOffset: 4
          }
        ]
      })
    when "total_watched_anime"
      @total_watched_anime_time_mins = @user_statistics&.[]("minutesWatched").to_i
      @total_watched_anime_time = format_date(@total_watched_anime_time_mins * 60)
      @total_watched_anime_ep = @user_statistics&.[]("episodesWatched").to_i

      statuses = @user_statistics["statuses"].to_a
      @total_completed_anime = statuses.find { |x| x["status"] == "COMPLETED" }&.[]("count").to_i
      @total_planning_anime = statuses.find { |x| x["status"] == "PLANNING" }&.[]("count").to_i
      @total_dropped_anime = statuses.find { |x| x["status"] == "DROPPED" }&.[]("count").to_i
      @total_current_anime = statuses.find { |x| x["status"] == "CURRENT" }&.[]("count").to_i
      @total_paused_anime = statuses.find { |x| x["status"] == "PAUSED" }&.[]("count").to_i
    when "total_watched_anime_movie"
      @total_watched_anime_movie_time_mins = @user_statistics["formats"]
                                               .to_a
                                               .select { |x| ANIME_FORMATS.exclude? x["format"] }
                                               .map { |x| x&.[]("minutesWatched").to_i }.sum
      @total_watched_anime_movie_time = format_date(@total_watched_anime_movie_time_mins * 60)
      @total_watched_anime_movie = @user_statistics["formats"].to_a
                                     .select { |x| ANIME_FORMATS.exclude? x["format"] }
                                     .map { |x| x&.[]("count").to_i }.sum
    else return render nothing: true
    end

    render template: "home/#{turbo_frame_request_id}", layout: false if turbo_frame_request?
  rescue StandardError => error
    render_empty(error)
  end

  def anilist_user_activities
    now = Time.zone.now.beginning_of_day
    last_week_start = (now - 1.week).beginning_of_week.to_i
    last_week_end = (now - 1.week).end_of_week.to_i
    turbo_frame = turbo_frame_request_id

    case turbo_frame_request_id
    when "last_watched"
      last_watched = AnilistActivity
                       .order(id: :desc)
                       .where.in("media.format": ANIME_FORMATS)
                       .and.not.in(status: IGNORED_USER_STATUS)
                       .limit(1)
                       &.first
      @last_watched = user_activity_fetch_fanart(activity: last_watched)
    when "last_watched_movie"
      last_watched_movie = AnilistActivity
                             .order(id: :desc)
                             .where("media.format": "MOVIE")
                             .and.not.in(status: IGNORED_USER_STATUS)
                             .limit(1)
                             &.first
      @last_watched_movie = user_activity_fetch_fanart(activity: last_watched_movie)
    when /watched_anime_\d+_\d+/
      @index = turbo_frame_request_id.scan(/\d+/).first.to_i
      @watched_anime = AnilistActivity
                         .order(id: :desc)
                         .where.in("media.format": ANIME_FORMATS)
                         .and.not.in(status: IGNORED_USER_STATUS)
                         &.each_slice(6)
                         &.to_a
                         &.[](@index)
      turbo_frame = "watched_anime"
    when /watched_movie_\d+_\d+/
      @index = turbo_frame_request_id.scan(/\d+/).first.to_i
      @watched_movie = AnilistActivity
                         .order(id: :desc)
                         .where.not.in("media.format": ANIME_FORMATS)
                         .and.not.in(status: IGNORED_USER_STATUS)
                         &.each_slice(6)
                         &.to_a
                         &.[](@index)
      turbo_frame = "watched_movie"
    when "total_watched_anime_last_week"
      watched_last_week = AnilistActivity
                            .order(id: :desc)
                            .where(createdAt: { "$gte": last_week_start, "$lte": last_week_end })
                            .and.not.in(status: IGNORED_USER_STATUS)
      @total_watched_anime_time_last_week_mins = watched_last_week
                                                   .map { |x| x&.[]("media")&.[]("duration").to_i }
                                                   .sum
      @total_watched_anime_time_last_week = format_date(@total_watched_anime_time_last_week_mins * 60)
      @total_watched_anime_ep_last_week = watched_last_week.size
    when "total_watched_anime_movie_last_week"
      watched_last_week = AnilistActivity
                            .order(id: :desc)
                            .where.not.in("media.format": ANIME_FORMATS)
                            .and(createdAt: { "$gte": last_week_start, "$lte": last_week_end })
                            .and.not.in(status: IGNORED_USER_STATUS)
      @total_watched_anime_movie_time_last_week_mins = watched_last_week
                                                         .map { |x| x&.[]("media")&.[]("duration").to_i }
                                                         .sum
      @total_watched_anime_movie_time_last_week = format_date(@total_watched_anime_movie_time_last_week_mins * 60)
      @total_watched_anime_movie_last_week = watched_last_week.size
    else return render nothing: true
    end

    render template: "home/#{turbo_frame}", layout: false if turbo_frame_request?
  rescue StandardError => error
    render_empty(error)
  end

  def watched_anime_section
    @watched_anime = AnilistActivity
                       .order(id: :desc)
                       .where.in("media.format": ANIME_FORMATS)
                       .and.not.in(status: IGNORED_USER_STATUS)
    render template: "home/#{turbo_frame_request_id}", layout: false if turbo_frame_request?
  rescue StandardError => error
    render_empty(error)
  end

  def watched_movie_section
    @watched_movie = AnilistActivity
                       .order(id: :desc)
                       .where
                       .not.in("media.format": ANIME_FORMATS)
                       .and
                       .not.in(status: IGNORED_USER_STATUS)
    render template: "home/#{turbo_frame_request_id}", layout: false if turbo_frame_request?
  rescue StandardError => error
    render_empty(error)
  end

  def lastfm_stats
    @album_art = nil
    lastfm = LastFM::Client.new
    @lastfm_recent = lastfm.get_recent_tracks(user: ENV.fetch("LASTFM_USERNAME"), limit: 1, extended: 1)

    if @lastfm_recent.is_a? Array
      timestamp = @lastfm_recent.last["date"]["uts"].to_i
      @lastfm_recent = @lastfm_recent.first
    else
      timestamp = @lastfm_recent["date"]["uts"].to_i
    end

    album_art = @lastfm_recent&.[]("image")&.[](3)&.[]("#text")
    if album_art.present? && album_art.exclude?("2a96cbd8b46e442fc41c2b86b821562f")
      @album_art = album_art.split("300x300").join("400x400")
    end

    @elapsed_time = Time.zone.at(Time.zone.now - Time.zone.at(timestamp)).utc.strftime "%M:%S"

    render template: "home/lastfm_stats", layout: false if turbo_frame_request?
  rescue LastFM::ApiError

app/views/home/_stats_section.html.erb
<section class="flex-1">
  <div class="flex flex-row flex-wrap w-full">
    <div class=" phone:w-full bg-[#395B64] tablet:w-1/2 desktop:w-1/3 desktop-lg:w-1/4 min-h-[400px] tablet:h-[400px] overflow-hidden ">
      <div class="flex flex-col w-full h-full px-4 py-4 text-white">
        <h2 class="text-lg font-bold">ABOUT ME</h2>
        <h3 class="flex flex-col grow">
          <%= ENV.fetch("ABOUT_ME", "<span></span>").html_safe.force_encoding("UTF-8") %>
        </h3>
      </div>
    </div>

    <div class=" phone:w-full bg-[#774360] tablet:w-1/2 desktop:w-1/3 desktop-lg:w-1/4 min-h-[400px] tablet:h-[400px] overflow-hidden ">
      <turbo-frame id="lastfm_stats" src="<%= lastfm_stats_path %>" loading="lazy">
        <div class="flex flex-col w-full h-full px-4 py-4" x-data="">
          <a href="https://www.last.fm/user/CyanNyan" rel="noopener noreferrer" target="_blank" class="text-lg font-bold text-left text-white hover:underline">
            <h2>LAST.FM</h2>
          </a>
          <div class="flex items-center justify-center grow">
            <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
          </div>
        </div>
      </turbo-frame>
    </div>

    <div class=" phone:w-full bg-[#4C3575] tablet:w-1/2 desktop:w-1/3 desktop-lg:w-1/4 min-h-[400px] tablet:h-[400px] overflow-x-auto overflow-y-hidden " x-data="">
      <turbo-frame id="favorite_anime_genres" src="<%= anilist_user_statistics_path %>" loading="lazy">
        <div class="flex flex-col w-full h-full px-4 py-4" x-data="">
          <a href="https://anilist.co/user/CyanNyan/stats/anime/genres" rel="noopener noreferrer" target="_blank" class="text-lg font-bold text-left text-white hover:underline">
            <h2>FAVORITE ANIME GENRES</h2>
          </a>
          <div class="flex items-center justify-center grow">
            <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
          </div>
        </div>
      </turbo-frame>
    </div>

    <div class=" phone:w-full bg-[#570530] tablet:w-1/2 desktop:w-1/3 desktop-lg:w-1/4 min-h-[400px] tablet:h-[400px] overflow-hidden ">
      <turbo-frame id="last_watched" src="<%= anilist_user_activities_path %>" loading="lazy">
        <div class="flex flex-col w-full h-full px-4 py-4">
          <h2 class="text-lg font-bold text-left text-white">LAST WATCHED ANIME</h2>
          <div class="flex items-center justify-center grow">
            <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
          </div>
        </div>
      </turbo-frame>
    </div>

    <div class=" phone:w-full bg-[#2D4263] tablet:w-1/2 desktop:w-1/3 desktop-lg:w-1/4 min-h-[400px] tablet:h-[400px] overflow-x-auto overflow-y-hidden " x-data="">
      <turbo-frame id="favorite_anime_studios" src="<%= anilist_user_statistics_path %>" loading="lazy">
        <div class="flex flex-col w-full h-full px-4 py-4" x-data="">
          <a href="https://anilist.co/user/CyanNyan/stats/anime/studios" rel="noopener noreferrer" target="_blank" class="text-lg font-bold text-left text-white hover:underline">
            <h2>FAVORITE ANIME STUDIOS</h2>
          </a>
          <div class="flex items-center justify-center grow">
            <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
          </div>
        </div>
      </turbo-frame>
    </div>

    <div class=" phone:w-full bg-[#5C3D2E] tablet:w-1/2 desktop:w-1/3 desktop-lg:w-1/4 min-h-[400px] tablet:h-[400px] overflow-hidden ">
      <turbo-frame id="lastfm_top_artists" src="<%= lastfm_top_artists_path %>" loading="lazy">
        <div class="flex flex-col w-full h-full px-4 py-4 text-white" x-data="">
          <a href="https://www.last.fm/user/CyanNyan/library/artists?date_preset=ALL" rel="noopener noreferrer" target="_blank" class="text-lg font-bold text-left hover:underline">
            <h2>LAST.FM (TOP ARTISTS OF ALL TIME)</h2>
          </a>
          <div class="flex items-center justify-center grow">
            <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
          </div>
        </div>
      </turbo-frame>
    </div>

    <div class=" dark:[color-scheme:dark] phone:w-full bg-[#346751] tablet:w-1/2 desktop:w-1/3 desktop-lg:w-1/4 min-h-[400px] tablet:h-[400px] overflow-x-hidden overflow-y-auto ">
      <turbo-frame id="last_watched_movie" src="<%= anilist_user_activities_path %>" loading="lazy">
        <div class="flex flex-col w-full h-full px-4 py-4">
          <h2 class="text-lg font-bold text-left text-white">LAST WATCHED ANIME MOVIE</h2>
          <div class="flex items-center justify-center grow">
            <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
          </div>
        </div>
      </turbo-frame>
    </div>

    <div class=" dark:[color-scheme:dark] phone:w-full bg-white tablet:w-1/2 desktop:w-2/3 desktop-lg:w-1/4 min-h-[400px] tablet:h-[400px] overflow-x-hidden overflow-y-auto ">
      <div class="flex flex-col w-full h-full text-center text-white">
        <div class="bg-[#019edf] flex-1 w-full flex flex-col px-4 py-4" x-data="">
          <h2>
            <a href="https://anilist.co/user/CyanNyan/stats/anime/overview" rel="noopener noreferrer" target="_blank" class="text-lg font-bold hover:underline">WATCHED ANIME</a>
          </h2>
          <div class="flex flex-row flex-wrap gap-4 grow">
            <div class="flex flex-col items-center justify-center grow">
              <turbo-frame id="total_watched_anime_last_week" src="<%= anilist_user_activities_path %>" loading="lazy">
                <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
              </turbo-frame>
            </div>
            <div class="flex flex-col items-center justify-center grow">
              <turbo-frame id="total_watched_anime" src="<%= anilist_user_statistics_path %>" loading="lazy">
                <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
              </turbo-frame>
            </div>
          </div>
        </div>
        <div class="bg-[#0199d8] flex-1 w-full flex flex-col px-4 py-4">
          <h2>
            <a href="https://anilist.co/user/CyanNyan/stats/anime/overview" rel="noopener noreferrer" target="_blank" class="text-lg font-bold hover:underline">WATCHED ANIME MOVIES&nbsp;/&nbsp;OVA&nbsp;/&nbsp;SPECIALS</a>
          </h2>
          <div class="flex flex-row flex-wrap gap-4 grow">
            <div class="flex flex-col items-center justify-center grow">
              <turbo-frame id="total_watched_anime_movie_last_week" src="<%= anilist_user_activities_path %>" loading="lazy">
                <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
              </turbo-frame>
            </div>
            <div class="flex flex-col items-center justify-center grow">
              <turbo-frame id="total_watched_anime_movie" src="<%= anilist_user_statistics_path %>" loading="lazy">
                <%= render partial: "layouts/spinner", locals: { add_class: "w-10 h-10 border-8 text-white" } %>
              </turbo-frame>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render "partials/divider" %>

app/views/home/_watched_section.html.erb
<section class="flex-1 mb-20">
  <div class="container w-full mx-auto">
    <h2 class="flex flex-row items-center gap-1 mt-10 mb-5 text-2xl dark:text-white phone:text-center tablet:text-left">
      <iconify-icon icon="mdi:timer-play" width="24"></iconify-icon>
      Recently watched episodes
    </h2>
    <turbo-frame id="watched_anime_section" src="<%= watched_anime_section_path %>" loading="lazy" class="relative min-h-[322px] block" x-data="{swiper: null}">
      <div></div>
    </turbo-frame>

    <h2 class="flex flex-row items-center gap-1 mt-10 mb-5 text-2xl dark:text-white phone:text-center tablet:text-left">
      <iconify-icon icon="mdi:timer-play" width="24"></iconify-icon>
      Recently watched movies&nbsp;/&nbsp;ova&nbsp;/&nbsp;specials
    </h2>
    <turbo-frame id="watched_movie_section" src="<%= watched_movie_section_path %>" loading="lazy" class="relative min-h-[322px] block" x-data="{swiper: null}">
      <div></div>
    </turbo-frame>
  </div>
</section>

app/views/home/favorite_anime_genres.html.erb
<turbo-frame id="favorite_anime_genres">
  <div class="flex flex-col w-full h-full px-4 py-4 text-white">
    <a href="https://anilist.co/user/CyanNyan/stats/anime/genres" rel="noopener noreferrer" target="_blank" class="text-lg font-bold text-left text-white hover:underline">
      <h2>FAVORITE ANIME GENRES</h2>
    </a>
    <div class="flex flex-row">
      <div class="grow flex flex-col min-w-[150px]">
        <div>
          <ul>
            <% @genre_list&.each do |genre| %>
              <li class="flex flex-row gap-2 mt-2">
                <div class="min-w-[20px] min-h-[20px] my-auto" style="background: <%= genre[:backgroundColor] %>"></div>
                <h3><%= genre[:label] %></h3>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="mx-auto max-w-[300px]">
        <canvas id="favoriteGenres" aria-label="Favorite Anime Genres">
          Your browser does not support the canvas element.
        </canvas>
      </div>
    </div>
  </div>

  <script>
    document.addEventListener('turbo:frame-load', (event) => {
      if (event.target.id === "favorite_anime_genres") {
        const genre = document.getElementById('favoriteGenres').getContext('2d');
        const genreChart = new Chart(genre, {
          type: 'pie',
          options: {
            responsive: true,
            rotation: -90,
            layout: {
              padding: 20
            },
            plugins: {
              legend: {
                display: false,
              }
            },
            elements: {
              arc: {
                borderWidth: 4,
                borderColor: "#4c3575"
              }
            }
          },
          data: JSON.parse(`<%= raw @genre_chart_data %>`),
          plugins: []
        });
      }
    });
  </script>
</turbo-frame>

app/views/home/favorite_anime_studios.html.erb
<turbo-frame id="favorite_anime_studios">
  <div class="flex flex-col w-full h-full px-4 py-4 text-white">
    <a href="https://anilist.co/user/CyanNyan/stats/anime/studios" rel="noopener noreferrer" target="_blank" class="text-lg font-bold text-left text-white hover:underline">
      <h2>FAVORITE ANIME STUDIOS</h2>
    </a>
    <div class="flex flex-row">
      <div class="grow flex flex-col min-w-[150px]">
        <div>
          <ul>
            <% @studio_list&.each do |studio| %>
              <li class="flex flex-row gap-2 mt-2">
                <div class="min-w-[20px] min-h-[20px] my-auto" style="background: <%= studio[:backgroundColor] %>"></div>
                <h3><%= studio[:label] %></h3>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="mx-auto max-w-[300px]">
        <canvas id="favoriteStudios" aria-label="Favorite Anime Studios">
          Your browser does not support the canvas element.
        </canvas>
      </div>
    </div>
  </div>

  <script>
    document.addEventListener('turbo:frame-load', (event) => {
      if (event.target.id === "favorite_anime_studios") {
        const studio = document.getElementById('favoriteStudios').getContext('2d');
        const studioChart = new Chart(studio, {
          type: 'pie',
          options: {
            responsive: true,
            rotation: -90,
            layout: {
              padding: 20
            },
            plugins: {
              legend: {
                display: false,
              }
            },
            elements: {
              arc: {
                borderWidth: 4,
                borderColor: "#2d4263"
              }
            }
          },
          data: JSON.parse(`<%= raw @studio_chart_data %>`),
          plugins: []
        });
      }
    });
  </script>
</turbo-frame>

app/views/home/index.html.erb
<% bgs = (1..15).to_a.shuffle %>

<%= render "profile_section", bgs: %>
<%= render "stats_section" %>
<%= render "watched_section" %>

app/views/home/last_watched.html.erb
<% cover = @last_watched&.[]("media")&.[]("bannerImage") %>
<% cover = cover&.exclude?("anilist") ? cached_image_url_to_base64(cover) : cover %>
<turbo-frame id="last_watched" class="w-full h-full">
  <canvas id="canvas-bg" hidden></canvas>
  <div id="cover-bg" class="w-full h-full transition-all duration-500 bg-center bg-cover" style="opacity: 0; background: no-repeat center/75% url(<%= vite_asset_path("images/bvl-logo.webp") %>); background-color: darkred">
    <div class="<%= cover.present? ? "backdrop-brightness-50" : "backdrop-brightness-[0.2]" %> flex flex-col w-full h-full px-4 py-4 text-white">
      <h2 class="text-lg font-bold text-shadow shadow-black">LAST WATCHED ANIME</h2>

      <% if @last_watched.present? %>
        <a class="hover:underline" href="<%= @last_watched&.[]("media")&.[]("siteUrl") %>" rel="noopener noreferrer">
          <h3 class="text-4xl font-bold text-shadow shadow-black"><%= @last_watched&.[]("media")&.[]("title")&.[]("userPreferred") %></h3>
          <span class="text-2xl text-gray-200/80 text-shadow shadow-black"><%= @last_watched&.[]("media")&.[]("seasonYear") %></span>
        </a>
        <div class="self-end mt-auto">
          <a class="text-lg hover:underline grow text-shadow shadow-black" href="<%= @last_watched&.[]("siteUrl") %>" rel="noopener noreferrer">MORE INFO</a>
        </div>
      <% end %>
    </div>
  </div>

  <script>
    (async () => {
      await CropImage("<%= cover %>", "canvas-bg", "cover-bg", 1280, 1080);
    })();
  </script>
</turbo-frame>

app/views/home/site.webmanifest.erb
{ "lang": "en", "name": "Cyan★Nyan♪ | aldwin7894", "short_name": "aldwin7894", "description": "aldwin7894's personal web app which contains some random stats about anime, games and music (and probably some useful tools in the near future :3).", "theme_color": "#ffffff", "background_color": "#ffffff", "display": "standalone", "categories": [ "games", "social", "aldwin7894", "cyannyan", "cyannyann", "anilist", "al", "myanimelist", "mal", "last.fm", "project-cyan" ], "icons": [ { "src":
"/android-chrome-192x192.png", "sizes": "192x192", "type": "image/png" }, { "src": "/android-chrome-512x512.png", "sizes": "512x512", "type": "image/png" } ], "shortcuts": [ { "name": "Home", "url": "/" }, { "name": "AniList Follow Checker", "url": "/anilist", "description": "Checks your following and followers list on AniList, and also lists out users that you don't follow yet or doesn't follow you." } ] }

app/views/home/total_watched_anime_movie.html.erb
<turbo-frame id="total_watched_anime_movie">
  <h3 class="font-mono text-lg" data-tippy="tooltip" data-tippy-content="<%= @total_watched_anime_movie_time_mins&.to_fs(:delimited) %>m">
    <% @total_watched_anime_movie_time.each do |time, uom| %>
      <span class="text-2xl font-bold"><%= time %></span><%= uom %>
    <% end %>
  </h3>
  <h3>ALL TIME</h3>
  <h3 class="text-white text-opacity-80">
    <%= @total_watched_anime_movie&.to_fs(:delimited) %>
    movies / ova / specials
  </h3>
</turbo-frame>